apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    env: production
spec:
  containers:
  - name: nginx
    image: nginx    
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
  